config/routes.rb
Rails.application.routes.draw do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

   resources :users
   get '/nowy-uczen', to: 'users#new'
   post '/nowy-uczen', to: 'users#create'
   resources :pictures
   get '/new-picture', to: 'pictures#new'
   post '/new-picture', to: 'pictures#create'
   


end

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#myNavbar" aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="https://cocomonkeyblog.files.wordpress.com/" id="logo"> <img src="https://cocomonkeyblog.files.wordpress.com/2017/07/cropped-krzywe-2-monkey1.png?w=1024&h=228" alt="CocoMonkey logo" style="width:303px;height:68px;border:0" class="img-fluid"></a>


    <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item nav-link"><%= link_to "O SZKOLE", "https://cocomonkeyblog.wordpress.com/about/" %></li>
          <li class="nav-item nav-link"><%= link_to "CENNIK", "https://cocomonkeyblog.wordpress.com/cennik/" %></li>
          <li class="nav-item nav-link"><%= link_to "KONTAKT", "https://cocomonkeyblog.wordpress.com/contact/" %></li>
          <li class="nav-item nav-link"><%= link_to "BLOG", "https://cocomonkeyblog.wordpress.com/blog/" %></li>

          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              Moje konto
            </a>
            <div class="dropdown-menu">
              <a><%= link_to "Profile", current_user, class: 'dropdown-item' %></a>
              <a><%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %></a>
              <a> <%= link_to "Users", users_path, class: 'dropdown-item' %></a>
              <a class="dropdown-divider"></a>
              <a><%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %></a>
            </div>
          </li>


          <% else %>
            <li class="nav-item nav-link"><%= link_to "Zaloguj się", login_path %></li>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              ĆWICZENIA
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="/">Angielski</a>
              <a class="dropdown-item" href="https://coco-monkey.herokuapp.com/">Matematyka</a>
            </div>
          </li>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocoMonkey - ćwiczenia z angielskiego</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- 3 kolejne są po to żeby działało dropdown menu ĆWICZENIA -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</head>

  <body>
     <%= render 'layouts/header' %>
     <div class="container">
       <h1 class="text-center m-5">Let's do some English!</h1>
       <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
       <%= yield %>
     </div>
     <%= debug(params) if Rails.env.development? %>
     <%= console if Rails.env.development? %>
  </body>
</html>